// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVNuJAV4Ocn2qq6FoZFVLOCOOm2kIPRE',
    appId: '1:427872411983:web:8d3d12a267f0fb46f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    authDomain: 'tay-rona-flutter.firebaseapp.com',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    measurementId: 'G-NNLR169V9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3GsIJaOaJOaWeWdS4ElcRWxor3Gx-IoA',
    appId: '1:427872411983:android:6e1f7a19fd918d8af3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XehgtpAceKRJzqx8RTgGNwA70o76-XA',
    appId: '1:427872411983:ios:6edee1caad988aa8f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    androidClientId: '427872411983-0v9n96qjbjqqoc9i1aqa6fqst5u29v00.apps.googleusercontent.com',
    iosClientId: '427872411983-vm5ddvnqb199mudl4cusnhf6gp0541md.apps.googleusercontent.com',
    iosBundleId: 'com.admintay.tayRonaAdministrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XehgtpAceKRJzqx8RTgGNwA70o76-XA',
    appId: '1:427872411983:ios:6edee1caad988aa8f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    androidClientId: '427872411983-0v9n96qjbjqqoc9i1aqa6fqst5u29v00.apps.googleusercontent.com',
    iosClientId: '427872411983-vm5ddvnqb199mudl4cusnhf6gp0541md.apps.googleusercontent.com',
    iosBundleId: 'com.admintay.tayRonaAdministrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgVNuJAV4Ocn2qq6FoZFVLOCOOm2kIPRE',
    appId: '1:427872411983:web:9f347c276ec5aa2bf3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    authDomain: 'tay-rona-flutter.firebaseapp.com',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    measurementId: 'G-ZGHGP6DSM8',
  );
}
